version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "9000:9000"
    volumes:
      - ./vina-biosystems:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - NODE_ENV=development
    stdin_open: true
    tty: true
    depends_on:
      - backend

  backend:
    build:
      context: ./backend  # Aponta para a pasta backend
      dockerfile: Dockerfile  # Usa o Dockerfile dentro da pasta backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped  # Recomendado para backend